---
title: "Final Project"
author: "Samruddhi Shinde"
date: "5/1/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading packages

```{r}
library(here)
library(tidyverse)
```

Loading in Datasets

```{r}
prison_pop <- read_csv(here("data", "prison_populations.csv"))
covid_prison_cases <- read_csv(here("data", "covid_prison_cases.csv"))
staff_pop <- read_csv(here("data", "staff_populations.csv"))
```

I am only looking at COVID-19 rates in California so I will be filtering the covid_prison_cases dataset. I am also only looking at staff & prisoner cases/deaths
so I will be selecting the appropriate columns.

```{r}
cali_covid_cases <- covid_prison_cases %>%
  filter(name == "California") %>%
  select(total_staff_cases, total_staff_deaths, total_prisoner_cases, total_prisoner_deaths, as_of_date)
```

```{r}
cali_staff_pop <- staff_pop %>%
  filter(name == "California") %>%
  select(april_pop, as_of_date)
```

```{r}
cali_prison_pop <- prison_pop %>%
  filter(name == "California") %>%
  select(name, march_pop, april_pop, june_pop, july_pop, aug_pop, sept_pop, oct_pop, nov_pop)
```

--------------------------------------------------------------------------------

Summary table of average & sd of staff cases/deaths and prisoner cases/deaths

```{r}
cali_covid_cases %>%
  summarize(Average_Staff_Cases = mean(total_staff_cases, na.rm = TRUE),
            SD_Staff_Cases = sd(total_staff_cases, na.rm = TRUE),
            Average_Staff_Deaths = mean(total_staff_deaths, na.rm = TRUE),
            SD_Staff_Deaths = sd(total_staff_deaths, na.rm = TRUE),
            Average_Prisoner_Cases = mean(total_prisoner_cases, na.rm = TRUE),
            SD_Prisoner_Cases = sd(total_prisoner_cases, na.rm = TRUE),
            Average_Prisoner_Deaths = mean(total_prisoner_deaths, na.rm = TRUE),
            SD_Prisoner_Deaths = sd(total_prisoner_deaths, na.rm = TRUE))
```

Scatter Plot for total prisoner cases per date

```{r}
cali_covid_cases %>%
  ggplot(aes
         (x = as_of_date,
           y = total_prisoner_cases)) +
  geom_point() +
  # scale_x_date(name = "Date",
  #              date_breaks = "12 months",
  #              date_labels = "%m-%Y") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_x_discrete(labels=c("01/05/2021" = "January 2021"))

      
```

--------------------------------------------------------------------------------
Data Set of Covid-19 Cases for every State in March 2021
```{r}
march2021_covid_cases <- covid_prison_cases %>%
  filter(as_of_date == "03/01/2021"| 
        as_of_date =="03/02/2021"| 
        as_of_date =="03/03/2021"| 
        as_of_date == "03/04/2021"| 
        as_of_date =="03/05/2021") 
```


Bar plot Covid-19 Cases for every State in March 2021
```{r}
march2021_covid_cases %>%
  ggplot(aes
         (x = abbreviation, 
          y = total_prisoner_cases,
          color = abbreviation,
           fill = abbreviation)) +
  geom_bar(stat="identity", alpha=.8, width=.6) +
  theme(axis.text.x  = element_text(angle=-90, hjust=0.5, size=7,colour="black")) +
  ylab("Number of COVID-19 Cases in March 2021") +
  xlab("State") +
  theme(legend.title = element_blank())
```

Deaths in California in March 2021
```{r}
cali_deaths <- covid_prison_cases %>%
  filter(name == "California") %>%
  select(total_staff_deaths, total_prisoner_deaths, as_of_date) %>%
  filter(as_of_date)

# cali_march2021_deaths <- as.data.frame(t(cali_march2021_deaths))

# cali_column_names <- data.frame("Type", "Number of Deaths")
# 
# cali_march2021_deaths <- merge(cali_march2021_deaths, cali_march2021_deaths)
```

```{r}
cali_march2021_deaths %>%
  ggplot(aes
         (y = total_staff_deaths, x = total)) +
  geom_bar()
```

