# Final Project Repository

This repository contains the data needed for my final project. As of now, there are two folders:
- data: holds datasets 
- output: will holds future output files

# Data 

The data I am looking at was collected by The Marshall Project, a non-profit organization that looks at the United States criminal justice system. This data in particular looks at the infection rates of COVID-19 in prisons across the nation.

There are four datasets:
- covid_prison_cases.csv contains weekly time series data on tests, infections and deaths in prisons. - prison_populations.csv contains snapshots of the population of people incarcerated in each of these prison systems for whom data on COVID testing and cases are available. This varies by state.
- staff_populations.csv contains a one-time, recent snapshot of the headcount of workers for each prison agency, collected as close to April 15 as possible.
-covid_prison_rates.csv contains the rates of cases and deaths for prisoners. There is one row for every state and federal prison system and an additional row with the National totals.